import { readFile, writeFile } from 'node:fs/promises'
import { Script } from 'node:vm'
import { validateMarket } from './src/catalog.mjs'
const root = new URL('./', import.meta.url)
const read = p => readFile(new URL(p, root), 'utf8')
const catalog = validateMarket(JSON.parse(await read('../../market/catalog.json')))
const core = (await read('src/catalog.mjs')).replaceAll('export ', '')
const ui = (await read('src/plugin.mjs')).replace(/^import .*\n/, '').replace('export ', '')
const out = `// Generated by build.mjs from hub/market/catalog.json; do not edit.\nwindow.__ModuleLoader__.load({id:'qcu-market',factory(require){\nconst React=require('react');\n${core}\n${ui}\nreturn createMarketPlugin(React,{kind:'bundled',value:${JSON.stringify(catalog)}},globalThis.navigator?.clipboard);\n}});\n`
new Script(out, { filename: 'client.js' })
await writeFile(new URL('client.js', root), out)
console.log('QCU client built and syntax-compiled; 8 entries, no external runtime imports except host React.')
