// Generated QCU market pilot.4; explicit user confirmation, no model/session dependency.
window.__ModuleLoader__.load({id:'qcu-market',factory(require){
const React=require('react');
// Generated by scripts/pack-coach-v2.py; fixed trust root, not remote data.
const release = Object.freeze({"id": "qcu-study-coach", "version": "0.1.0-pilot.2", "skill": "qcu-study-coach", "skillSha256": "80ebebe91ae9edd71670cf22f7e5c7880d527e39c483fa193e6e819e8cd7ef4b", "provider": "qcu-study-coach@0.1.0-pilot.2", "origin": "http://192.168.1.68:8080", "file": "qcu-study-coach-0.1.0-pilot.2-4ac9b2489ece90098faea5f5d0cf79c6efb2989214eaf74f4e38c4841c2eb060.tgz", "bytes": 3445, "sha256": "4ac9b2489ece90098faea5f5d0cf79c6efb2989214eaf74f4e38c4841c2eb060", "runtime": "0.2.0-rc.2", "releaseStatus": "local-candidate-not-published", "license": "MIT"});

// Explicit public Typert descriptors, shared by Host and Client. No private renderer/controller imports.
const uuidCodec={mode:'strict',typeSymbol:'qcu-market#ReceiptId',create:()=>({parse(value){if(typeof value!=='string'||!/^([a-f0-9]{8}-)([a-f0-9]{4}-){3}[a-f0-9]{12}$/i.test(value))throw new Error('Expected receipt UUID');return value}})}
const resultCodec={mode:'strict',typeSymbol:'qcu-market#JsonReply',create:()=>({parse(value){if(typeof value!=='string'||value.length>16384)throw new Error('Invalid QCU reply');JSON.parse(value);return value}})}
const remoteContribution={package:'qcu-market',descriptors:['prepare','verify','cancel'].map(method=>({id:`qcu-market#qcuMarket/${method}`,service:'qcuMarket',namespace:'qcuMarket',method,invocation:{kind:'direct'},parameters:[{name:'id',wire:'id',source:'json',codec:uuidCodec}],...(method==='cancel'?{}:{cancellation:{parameter:'signal'}}),result:resultCodec}))}

const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b)
const failure=e=>e?.message||String(e)
function unwrap(answer){if(!answer?.ok)throw new Error(answer?.error?.message||'官方服务不可用');return answer.value}
async function readCoach(manager,entry=release){
  const bundles=unwrap(await manager.listBundles()),bundle=bundles.find(b=>b.name===entry.id)
  if(!bundle?.installed)return {state:'not-installed'}
  if(bundle.version!==entry.version)return {state:'conflict',reason:'已有其他版本，请在官方插件页单独审核处理。'}
  if(bundle.error)return {state:'failed',reason:bundle.error}
  if(!bundle.enabled)return {state:'installed-disabled'}
  const rows=unwrap(await manager.listPlugins()).filter(r=>r.moduleName===entry.id)
  if(rows.length!==1)return {state:'conflict',reason:'组件数量不符；不猜测组件标识。'}
  const row=rows[0]
  if(row.fiberPhase==='failed')return {state:'failed',reason:'官方加载器报告失败。'}
  if(!row.enabled)return {state:'row-disabled',entryId:row.entryId}
  return {state:row.fiberPhase==='active'?'component-active':'restart-or-pending',entryId:row.entryId}
}
class DirectMarketFlow {
  constructor(remote,{entry=release,uuid=()=>crypto.randomUUID(),now=()=>Date.now()}={}){
    this.remote=remote;this.entry=entry;this.uuid=uuid;this.now=now;this.listeners=new Set();this.state={phase:'idle',status:null,review:null,message:'',result:null};this.generation=0;this.pending=null;this.request=null;this.disposed=false
    this.unlisten=remote.$on?.('plugin-manager/install-state',p=>this.progress(p))
  }
  snapshot=()=>this.state
  subscribe=fn=>{this.listeners.add(fn);return()=>this.listeners.delete(fn)}
  set(next){if(this.disposed)return;this.state={...this.state,...next};for(const fn of this.listeners)fn()}
  guard(){if(this.disposed)throw new Error('市场已关闭');if(this.pending||this.request)throw new Error('已有操作进行中；请等待或核对结果')}
  valid(n){if(this.disposed||n!==this.generation)throw new Error('操作已取消或目录已变化')}
  checkReceipt(r){if(!r||!same(r.entry,this.entry)||!Number.isSafeInteger(r.expiresAt)||r.expiresAt<=this.now()||typeof r.path!=='string'||!r.path.startsWith('/')||!r.path.endsWith('/'+this.entry.file))throw new Error('包来源、目录或有效期已变化；请重新准备并确认')}
  async status(){this.guard();const n=++this.generation;this.pending={kind:'status'};this.set({phase:'checking',review:null,message:''});try{const s=await readCoach(this.remote.pluginManager,this.entry);this.valid(n);this.set({phase:'idle',status:s})}catch(e){if(n===this.generation)this.set({phase:'error',status:null,message:failure(e)})}finally{this.pending=null}}
  async prepare(){
    this.guard();const n=++this.generation,id=this.uuid(),abort=new AbortController();this.pending={kind:'prepare',id,abort};this.set({phase:'preparing',review:null,message:'',result:null})
    try{
      const status=await readCoach(this.remote.pluginManager,this.entry);this.valid(n);if(status.state!=='not-installed'){this.set({phase:'idle',status});return}
      const receipt=JSON.parse(unwrap(await this.remote.qcuMarket.prepare(id,abort.signal)));this.valid(n);this.checkReceipt(receipt);if(receipt.id!==id)throw new Error('包凭据不匹配')
      const inspected=unwrap(await this.remote.pluginManager.inspect(receipt.path,{},abort.signal));this.valid(n)
      if(inspected.status!=='accepted')throw new Error(inspected.reason||'官方包检查未通过')
      if(inspected.kind!=='tarball')throw new Error('官方检查的包格式不符')
      this.set({phase:'review',status,review:{kind:'install',receipt,inspected},message:''})
    }catch(e){if(n===this.generation)this.set({phase:'error',review:null,message:failure(e)})}finally{this.pending=null}
  }
  async confirmInstall(){
    this.guard();const review=this.state.review;if(this.state.phase!=='review'||review?.kind!=='install')throw new Error('请先查看并确认安装信息')
    const n=++this.generation,abort=new AbortController();this.pending={kind:'verify',id:review.receipt.id,abort};this.set({phase:'verifying',review:null,message:''})
    try{
      this.checkReceipt(review.receipt)
      const receipt=JSON.parse(unwrap(await this.remote.qcuMarket.verify(review.receipt.id,abort.signal)));this.valid(n);this.checkReceipt(receipt)
      if(!same(receipt,review.receipt))throw new Error('包凭据发生变化；原确认失效')
      const status=await readCoach(this.remote.pluginManager,this.entry);this.valid(n);if(status.state!=='not-installed')throw new Error('本实例状态已变化；原确认失效')
      const inspected=unwrap(await this.remote.pluginManager.inspect(receipt.path,{},abort.signal));this.valid(n)
      if(!same(inspected,review.inspected))throw new Error('官方包检查或安装源发生变化；请重新确认')
      this.checkReceipt(receipt)
      const request={id:this.uuid(),acknowledged:false,cancelRequested:false,cancelInFlight:false};this.request=request;this.pending=null;this.set({phase:'installing',message:'安装中；默认不启用。',result:null})
      let reply
      try{reply=await this.remote.pluginManager.installBundle(receipt.path,{enabled:false,requestId:request.id,registry:inspected.registry})}catch(e){if(this.request===request)this.set({phase:'unconfirmed',message:'安装结果未确认：'+failure(e)});return}
      if(this.request!==request||this.disposed)return
      if(!reply?.ok){this.set({phase:'unconfirmed',message:'安装结果未确认：'+(reply?.error?.message||'连接中断')});return}
      await this.settle(request,reply.value)
    }catch(e){if(n===this.generation)this.set({phase:'error',review:null,message:failure(e)})}finally{this.pending=null}
  }
  async settle(request,result){
    if(this.request!==request||this.disposed)return
    if(!result||!['applied','restart-required','overridden','failed','cancelled'].includes(result.application)){this.set({phase:'unconfirmed',message:'官方返回未知结果；不得重装。'});return}
    if(result.application==='cancelled'){this.request=null;this.set({phase:'cancelled',result,message:'官方已确认取消并恢复安装文件。'});return}
    if(result.application==='failed'||result.application==='overridden'){this.request=null;this.set({phase:'error',result,message:result.error?.message||result.error?.code||'官方拒绝或未按预期应用；不自动重试或授权脚本。'});return}
    if(result.stage!=='install'||result.bundle!==this.entry.id){this.set({phase:'unconfirmed',result,message:'返回的包或操作不符，请在官方详情核对。'});return}
    this.set({phase:'checking',result})
    try{const status=await readCoach(this.remote.pluginManager,this.entry);if(this.request!==request||this.disposed)return;this.request=null;this.set({phase:status.state==='installed-disabled'?'installed':'unconfirmed',status,result,message:status.state==='installed-disabled'?'已安装，未启用。': '安装返回成功，但当前状态不符；请核对。'})}catch(e){this.set({phase:'unconfirmed',result,message:failure(e)})}
  }
  async decline(){
    this.guard();const id=this.state.review?.receipt?.id;++this.generation;this.set({phase:'declined',review:null,message:'未授权安装；不会重试。'})
    if(id)await this.remote.qcuMarket.cancel(id).catch(()=>{})
  }
  async cancel(){
    if(this.request){this.request.cancelRequested=true;return this.cancelRequest(this.request)}
    const pending=this.pending,id=pending?.id||this.state.review?.receipt?.id;++this.generation;pending?.abort?.abort();this.set({phase:'cancelled',review:null,message:'尚未发起安装，操作已取消。'})
    if(id){try{unwrap(await this.remote.qcuMarket.cancel(id))}catch(e){this.set({message:'未发起安装；下载取消请求未确认：'+failure(e)})}}
  }
  async cancelRequest(request){
    if(this.request!==request||request.cancelInFlight)return
    request.cancelInFlight=true;this.set({phase:'cancelling',message:'等待官方确认取消；关闭界面不等于已停止。'})
    try{
      const value=unwrap(await this.remote.pluginManager.cancelInstall(request.id));if(this.request!==request||this.disposed)return
      if(value.status==='cancelled'){this.request=null;this.set({phase:'cancelled',message:'官方已确认取消。'});return}
      if(value.status==='too-late'){request.acknowledged=true;this.set({phase:'applying',message:'已进入收尾，无法确认取消；请核对结果。'});return}
      this.set({phase:'unconfirmed',message:'取消尚未确认，可能尚未接收请求；不会重新发起安装。'})
    }catch(e){if(this.request===request)this.set({phase:'unconfirmed',message:'取消未确认：'+failure(e)})}finally{request.cancelInFlight=false;if(request.cancelAfterAck){request.cancelAfterAck=false;void this.cancelRequest(request)}}
  }
  progress(p){const request=this.request;if(!request||p.requestId!==request.id)return;const first=!request.acknowledged;request.acknowledged=true;if(p.phase==='applying')this.set({phase:'applying',message:'官方正在应用安装结果。'});if(first&&request.cancelRequested){if(request.cancelInFlight)request.cancelAfterAck=true;else void this.cancelRequest(request)}}
  async reconcile(){const request=this.request;if(!request||request.reconciling)return;request.reconciling=true;try{const result=unwrap(await this.remote.pluginManager.waitForInstall(request.id));if(this.request!==request)return;if(result===null)this.set({phase:'unconfirmed',message:'后端没有保留该任务结果；不代表成功或取消，请在官方详情核对。'});else await this.settle(request,result)}catch(e){this.set({phase:'unconfirmed',message:failure(e)})}finally{request.reconciling=false}}
  async reviewEnable(kind){
    this.guard();const n=++this.generation;this.pending={kind:'enable-check'};this.set({phase:'checking',review:null,message:''})
    try{const status=await readCoach(this.remote.pluginManager,this.entry);this.valid(n);if((kind==='bundle'&&status.state!=='installed-disabled')||(kind==='row'&&status.state!=='row-disabled'))throw new Error('当前状态不支持此启用操作')
      this.set({phase:'review',status,review:{kind,entry:JSON.stringify(this.entry),status}})
    }catch(e){this.set({phase:'error',message:failure(e)})}finally{this.pending=null}
  }
  async confirmEnable(){
    this.guard();const review=this.state.review;if(this.state.phase!=='review'||!['bundle','row'].includes(review?.kind))throw new Error('缺少启用确认')
    const n=++this.generation;this.pending={kind:'enable'};this.set({phase:'enabling',review:null,message:''})
    try{const status=await readCoach(this.remote.pluginManager,this.entry);this.valid(n);if(review.entry!==JSON.stringify(this.entry)||!same(status,review.status))throw new Error('目录或组件状态变化；原确认失效')
      const result=unwrap(await (review.kind==='bundle'?this.remote.pluginManager.setBundleEnabled(this.entry.id,true):this.remote.pluginManager.setPluginEnabled(status.entryId,true)));this.valid(n)
      if(!['applied','restart-required'].includes(result.application)){this.set({phase:'error',result,message:result.error?.message||result.error?.code||'官方未应用启用；不重试。'});return}
      const next=await readCoach(this.remote.pluginManager,this.entry);this.valid(n);this.set({phase:'idle',status:next,result,message:result.application==='restart-required'?'需要你正常重启应用；此处不执行重启。':'启用操作已返回；以当前组件状态为准。'})
    }catch(e){if(n===this.generation)this.set({phase:'error',message:'启用结果需核对：'+failure(e)})}finally{this.pending=null}
  }
  invalidate(){++this.generation;this.pending?.abort?.abort();if(!this.request)this.set({phase:'error',status:null,review:null,message:'连接或目录变化，原确认已作废；已发出的启用操作需重新检查。'})}
  dispose(){this.disposed=true;++this.generation;this.pending?.abort?.abort();const id=this.pending?.id||this.state.review?.receipt?.id;if(id)void this.remote.qcuMarket.cancel(id).catch(()=>{});if(this.request)void this.remote.pluginManager.cancelInstall(this.request.id).catch(()=>{});this.unlisten?.();this.listeners.clear()}
}

// Original QCU line drawings, MIT. Generic learning symbols; not a school crest.
const iconPaths = {
  market: ['M4 4h6l2 2 2-2h6v15h-6l-2 2-2-2H4z', 'M12 6v15'],
  lesson: ['M4 4h16v12H4z', 'M8 21l4-5 4 5M8 8h8M8 12h5'],
  slides: ['M4 3h16v14H4z', 'M12 17v4M8 21h8M8 7h8M8 11h5'],
  document: ['M6 3h8l4 4v14H6z', 'M14 3v5h4M9 12h6M9 16h6'],
  data: ['M4 4h16v16H4z', 'M4 10h16M10 4v16M14 14h3M14 17h3'],
  reading: ['M3 5h7l2 2 2-2h7v14h-7l-2 2-2-2H3z', 'M12 7v14M6 9h3M6 13h3M15 9h3M15 13h3'],
  integrity: ['M12 3l8 3v6c0 5-8 9-8 9s-8-4-8-9V6z', 'M8 12l3 3 5-6'],
}
function sceneIcon(category) {
  return ({'备课与课堂活动':'lesson','课件制作':'slides','教学文档':'document','匿名教学数据':'data','阅读笔记与复习':'reading','学术诚信与引用':'integrity'})[category] ?? 'market'
}

// Scoped to our slot; official rc.2 semantic tokens inherit the user's theme.
const marketStyles = `
.qcu-market { box-sizing:border-box;height:100%;overflow:auto;padding:28px clamp(20px,4vw,48px) 48px;color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-base);font:inherit; }
.qcu-market * { box-sizing:border-box; }
.qcu-market .qcu-content { max-width:1280px;margin:0 auto; }
.qcu-market .qcu-head { display:flex;align-items:flex-start;justify-content:space-between;gap:20px;margin:24px 0; }
.qcu-market .qcu-wordmark { display:flex;align-items:center;gap:12px; }
.qcu-market h1 { margin:0;font-size:24px;line-height:32px;font-weight:600; }
.qcu-market h2 { margin:0;font-size:16px;line-height:24px;font-weight:600; }
.qcu-market p { line-height:1.6; }
.qcu-market .qcu-intro { margin:6px 0 0;color:var(--dsw-alias-label-secondary);font-size:14px; }
.qcu-market .qcu-note { padding:14px 16px;border:1px solid var(--dsw-alias-border-l2);border-radius:12px;background:var(--dsw-alias-bg-layer-1);font-size:13px;color:var(--dsw-alias-label-secondary); }
.qcu-market .qcu-filters { display:flex;flex-wrap:wrap;gap:8px;margin:24px 0 12px; }
.qcu-market button,.qcu-market summary { font:inherit; }
.qcu-market .qcu-control { display:inline-flex;align-items:center;justify-content:center;gap:8px;min-height:36px;padding:7px 12px;border:1px solid var(--dsw-alias-border-l3);border-radius:8px;background:transparent;color:var(--dsw-alias-label-primary);cursor:pointer;font-size:13px;line-height:20px; }
.qcu-market .qcu-control:hover { background:var(--dsw-alias-interactive-bg-hover); }
.qcu-market .qcu-control:active { background:var(--dsw-alias-interactive-bg-active); }
.qcu-market .qcu-control[aria-pressed="true"] { background:var(--dsw-alias-button-ghost-active-fill);border-color:var(--dsw-alias-button-ghost-active-border);color:var(--dsw-alias-brand-text); }
.qcu-market :is(button,summary,pre,input):focus-visible { outline:2px solid var(--dsw-alias-brand-primary);outline-offset:3px; }
.qcu-market .qcu-count { color:var(--dsw-alias-label-secondary);font-size:13px;margin:0 0 20px; }
.qcu-market .qcu-grid { display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,260px),1fr));gap:16px;align-items:start; }
.qcu-market .qcu-card { min-width:0;padding:16px;border:1px solid var(--dsw-alias-border-l2);border-radius:16px;background:var(--dsw-alias-bg-layer-1); }
.qcu-market .qcu-card-top { display:flex;align-items:center;gap:12px;margin-bottom:12px; }
.qcu-market .qcu-icon-tile { display:inline-flex;align-items:center;justify-content:center;width:44px;height:44px;flex:none;border-radius:12px;color:var(--dsw-alias-brand-text);background:var(--dsw-alias-button-ghost-active-fill); }
.qcu-market .qcu-badge { padding:4px 8px;border-radius:6px;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-secondary);font-size:12px;line-height:18px; }
.qcu-market .qcu-status { display:block;margin:4px 0 0;color:var(--dsw-alias-label-secondary);font-size:12px; }
.qcu-market .qcu-summary { margin:0 0 18px;font-size:14px; }
.qcu-market details { margin-top:12px; }
.qcu-market summary { cursor:pointer;line-height:22px; }
.qcu-market .qcu-guide > summary { padding:9px 12px;border-radius:8px;color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-layer-2);font-size:14px;font-weight:500; }
.qcu-market .qcu-guide[data-official="true"] > summary { color:var(--dsw-alias-label-primary-foreground);background:var(--dsw-alias-button-primary-fill); }
.qcu-market .qcu-guide[data-official="true"] > summary:hover { background:var(--dsw-alias-button-primary-hover); }
.qcu-market .qcu-guide > div { padding:4px 0; }
.qcu-market .qcu-guide p { font-size:13px;color:var(--dsw-alias-label-secondary); }
.qcu-market pre { white-space:pre-wrap;overflow-wrap:anywhere;user-select:text;padding:12px;border-radius:8px;background:var(--dsw-alias-bg-layer-2);font:inherit;font-size:13px;line-height:1.6; }
.qcu-market .qcu-meta { border-top:1px solid var(--dsw-alias-border-l2);padding-top:12px;font-size:12px;color:var(--dsw-alias-label-secondary); }
.qcu-market .qcu-meta dt { margin-top:12px;font-weight:600; }
.qcu-market .qcu-meta dd { margin:4px 0;overflow-wrap:anywhere;line-height:1.6; }
.qcu-market .qcu-foot { margin:24px 0 0;font-size:12px;color:var(--dsw-alias-label-secondary); }
.qcu-market .qcu-error { padding:16px;border:1px solid var(--dsw-alias-state-error-primary);border-radius:12px;color:var(--dsw-alias-state-error-primary); }
 .qcu-market .qcu-search { display:flex;align-items:center;flex-wrap:wrap;gap:10px;margin-top:24px;font-size:13px; }
.qcu-market .qcu-search input { min-width:0;flex:1 1 220px;max-width:440px;height:38px;padding:8px 12px;border:1px solid var(--dsw-alias-border-l3);border-radius:8px;color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-layer-1);font:inherit; }
.qcu-market .qcu-search input::placeholder { color:var(--dsw-alias-label-secondary); }
.qcu-market .qcu-card-heading { min-width:0; }
.qcu-market .qcu-icon-tile[data-scene="data"],.qcu-market .qcu-icon-tile[data-scene="integrity"] { color:var(--dsw-alias-state-success-primary);background:var(--dsw-alias-state-success-secondary); }
.qcu-market .qcu-icon-tile[data-scene="lesson"],.qcu-market .qcu-icon-tile[data-scene="reading"] { color:var(--dsw-alias-state-warn-label);background:var(--dsw-alias-state-warn-secondary); }
@media (max-width:560px) { .qcu-market .qcu-head { flex-direction:column; } .qcu-market .qcu-card { padding:16px; } }
`

const unavailableSnapshot=Object.freeze({phase:'unavailable',status:null,review:null,message:'缺少官方管理或QCU包准备服务；不能安装。'})
const noSubscribe=()=>()=>{}
const example='/qcu-study-coach\n我今天有30分钟复习一个知识点。请先问我课程与卡点，再给出可执行计划。'
function createLoopPlugin(React){
  const h=React.createElement
  function Icon(){return h('svg',{width:24,height:24,viewBox:'0 0 24 24',fill:'none',stroke:'currentColor',strokeWidth:1.7,'aria-hidden':true},...iconPaths.market.map((d,i)=>h('path',{key:i,d})))}
  function Market({flow,onBack,onDetails,unavailable}){
    const state=React.useSyncExternalStore(flow?.subscribe||noSubscribe,flow?.snapshot||(()=>unavailableSnapshot),flow?.snapshot||(()=>unavailableSnapshot))
    const [error,setError]=React.useState(''),[copied,setCopied]=React.useState('')
    React.useEffect(()=>()=>{if(flow?.state.review||flow?.pending?.kind==='prepare')void flow.cancel()},[flow])
    const act=fn=>{setError('');void Promise.resolve().then(fn).catch(e=>setError(e.message))}
    const labels={'not-installed':'未安装','installed-disabled':'已安装，未启用','row-disabled':'包已启用，教练组件未启用','component-active':'组件已加载；技能调用尚未验证','restart-or-pending':'组件待加载或需重启',conflict:'版本或组件冲突',failed:'加载失败'}
    const busy=['preparing','verifying','installing','cancelling','applying','checking','enabling','unconfirmed'].includes(state.phase)
    const review=state.review
    const button=(text,fn,disabled=false)=>h('button',{type:'button',className:'qcu-control',disabled,onClick:()=>act(fn)},text)
    return h('section',{className:'qcu-market','aria-label':'QCU市场'},h('style',null,marketStyles),h('div',{className:'qcu-content'},
      button('返回对话',onBack),h('header',{className:'qcu-head'},h('div',{className:'qcu-wordmark'},h(Icon),h('h1',null,'QCU市场')),h('span',{className:'qcu-badge'},'用户确认安装 · 本地候选')),
      h('p',null,'安装无需模型或 API Key。包由校内 Hub 独立托管，点击准备后按需下载；市场不捆绑教练安装包。'),
      h('article',{className:'qcu-card'},h('h2',null,'QCU学习方法教练'),h('p',null,`${release.id}@${release.version} · skill ${release.skill} · DSH ${release.runtime} · MIT`),h('p',null,'拆解任务、合理安排节奏与错题复盘；不代写应交作业。'),
        h('p',{role:'status','aria-live':'polite'},labels[state.status?.state]||'当前实例尚未核对'),h('p',null,state.status?.reason||''),
        h('p',{className:'qcu-note'},'独立教练包从校内 Hub 按需下载；是否可获取以本次下载与完整性校验结果为准。模拟测试通过；真机安装、重启及教学效果待验收。'),
        unavailable?h('p',{role:'alert'},unavailable):null,
        button('检查本实例',()=>flow.status(),!flow||(busy&&!(state.phase==='unconfirmed'&&!flow.request))||Boolean(review)),
        !review&&(!state.status||state.status.state==='not-installed')?button('下载并查看安装确认',()=>flow.prepare(),!flow||busy):null,
        state.status?.state==='installed-disabled'&&!review?button('查看启用包确认',()=>flow.reviewEnable('bundle'),busy):null,
        state.status?.state==='row-disabled'&&!review?button('查看启用组件确认',()=>flow.reviewEnable('row'),busy):null,
        button('官方插件详情',onDetails),
        review?h('section',{className:'qcu-note','aria-labelledby':'qcu-review-title'},h('h2',{id:'qcu-review-title'},review.kind==='install'?'请确认本次安装':'请确认本次启用'),
          h('p',null,`名称：QCU学习方法教练；包：${release.id}；版本：${release.version}；来源：QCU自有 / ${release.origin}`),
          h('p',{style:{overflowWrap:'anywhere'}},`SHA256：${release.sha256}；${release.bytes} 字节`),
          h('p',null,review.kind==='install'?`官方检查：本机固定包；registry ${review.inspected.registry??'采用当前pnpm配置'}。确认仅安装，enabled=false。`:`此处哈希是固定发行包标识，未重新读取已安装文件。本次只启用${review.kind==='bundle'?'包，不自动启用组件':`组件 ${review.status.entryId}`}。`),
          h('p',null,'代码在Host进程以应用用户权限运行，不受工作区沙箱隔离。官方安装会改写当前profile的依赖、锁文件、缓存和日志，可能访问配置的registry/镜像解析依赖；影响该profile全部会话。教练运行时只注册静态技能。'),
          h('p',null,'QCU代码范围是实现限制，不是OS沙箱。不会自动授权build脚本、版本豁免或扩大权限。审批人为本机用户，没有远程审核。'),
          button('拒绝／不安装',()=>flow.decline()),button(review.kind==='install'?'确认安装（保持未启用）':'确认本次启用',()=>review.kind==='install'?flow.confirmInstall():flow.confirmEnable())):null,
        ['preparing','verifying','installing','cancelling','applying','unconfirmed'].includes(state.phase)?button('请求取消',()=>flow.cancel(),state.phase==='cancelling'):null,
        flow?.request?button('核对官方任务结果',()=>flow.reconcile()):null,
        h('p',{role:'status','aria-live':'polite'},state.message),error?h('p',{role:'alert'},error):null,
        state.result?.pendingBuilds?.length?h('p',{role:'alert'},`需要额外脚本授权，市场已停止：${state.result.pendingBuilds.join(', ')}。请另行审核。`):null,
        state.result?.application==='restart-required'?h('p',null,'需要你正常重启应用；市场不会替你重启，也不声称已生效。'):null,
        h('details',null,h('summary',null,'使用示例（手动发送）'),h('p',null,'组件加载不等于目标会话技能已发现。安装不调用模型；发送学习任务本身需要官方聊天已有的模型配置。'),h('textarea',{readOnly:true,value:example,'aria-label':'学习示例',rows:4,style:{width:'100%'}}),button('复制学习示例',async()=>{try{if(!globalThis.navigator?.clipboard?.writeText)throw new Error('无剪贴板');await globalThis.navigator.clipboard.writeText(example);setCopied('已复制；请自行在对话中粘贴并发送。')}catch{setCopied('复制失败，请手动选中上方示例复制。')}}),h('p',{role:'status'},copied))),
      h('details',null,h('summary',null,'权限与官方Office帮助'),h('p',null,'QCU Host仅按请求下载校验固定包并写入 ~/.cache/qcu-market。无会话创建、技能正文、聊天或凭据读取，无模型工具。客户端只按操作读取官方插件清单，用户确认后才发起安装或独立启用。'),h('p',null,'office-pptx / office-docx / office-xlsx 为官方能力；本实例需另行核对，不在此重复安装。'))))
  }
  return {inject:['slots','layout'],async apply(ctx){
    let flow=null,unavailable=''
    const remote=ctx.get('remote')
    try{if(!remote?.$mount||!remote.pluginManager)throw new Error('缺少官方管理或QCU包准备服务；不能安装。');await remote.$mount(remoteContribution);flow=new DirectMarketFlow(remote)}catch(e){unavailable=e.message}
    ctx.effect(()=>()=>flow?.dispose())
    if(flow)ctx.effect(()=>ctx.on('connection/reset',()=>flow.invalidate()))
    ctx.slots.inject('main',()=>ctx.slots.register({name:'main',key:'qcu-market',inject:()=>({flow,unavailable,onBack:()=>ctx.layout.selectPanel(null),onDetails:()=>{const navigation=ctx.get('pluginNavigation');if(!navigation)throw new Error('官方详情服务不可用');navigation.openBundle(release.id)}})},Market))
    ctx.slots.inject('sidebar.panellist',()=>ctx.slots.register({name:'sidebar.panellist',id:'qcu-market',order:30,label:'QCU市场'},Icon))
  }}
}

return createLoopPlugin(React);
}});
