from pathlib import Path
import json,hashlib,tarfile,io,gzip,argparse
p=argparse.ArgumentParser();p.add_argument('--out',required=True,type=Path);a=p.parse_args()
r=Path(__file__).resolve().parents[1];src=r/'hub/plugins/qcu-study-coach-v2'
content=(r/'skills/qcu-study-coach/SKILL.md').read_text();digest=hashlib.sha256(content.encode()).hexdigest()
files={n:(src/n).read_bytes() for n in ['package.json','index.js','cordis.patch.yml','README.md','LICENSE']}
files['SKILL.md']=content.encode();files['skill-content.js']=('export const content = '+json.dumps(content,ensure_ascii=False)+';\nexport const contentSha256 = '+json.dumps(digest)+';\n').encode()
b=io.BytesIO()
with tarfile.open(fileobj=b,mode='w',format=tarfile.USTAR_FORMAT) as t:
 for n,body in sorted(files.items()):
  m=tarfile.TarInfo('package/'+n);m.size=len(body);m.mode=0o644;m.mtime=0;t.addfile(m,io.BytesIO(body))
raw=gzip.compress(b.getvalue(),mtime=0);sha=hashlib.sha256(raw).hexdigest();filename=f'qcu-study-coach-0.1.0-pilot.2-{sha}.tgz'
a.out.mkdir(parents=True,exist_ok=True);dest=a.out/filename
if dest.exists() and dest.read_bytes()!=raw:raise SystemExit('immutable artifact conflict')
dest.write_bytes(raw)
entry={'id':'qcu-study-coach','version':'0.1.0-pilot.2','skill':'qcu-study-coach','skillSha256':digest,'provider':'qcu-study-coach@0.1.0-pilot.2','origin':'http://192.168.1.68:8080','file':filename,'bytes':len(raw),'sha256':sha,'runtime':'0.2.0-rc.2','releaseStatus':'local-candidate-not-published','license':'MIT'}
(r/'hub/market/coach-release.json').write_text(json.dumps(entry,ensure_ascii=False,indent=2)+'\n')
(r/'hub/plugins/qcu-market/src/trusted-release.mjs').write_text('// Generated by scripts/pack-coach-v2.py; fixed trust root, not remote data.\nexport const release = Object.freeze('+json.dumps(entry,ensure_ascii=False)+');\n')
(a.out/'MANIFEST.json').write_text(json.dumps({'entry':entry,'members':{k:hashlib.sha256(v).hexdigest() for k,v in files.items()}},indent=2)+'\n')
print(json.dumps(entry))
